WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"

OPENWEATHER_API_KEY = "YOUR_API_KEY"
OPENWEATHER_BASE_URL = "http://api.openweathermap.org/data/2.5/weather"

DEFAULT_CITY = "Tokyo"
DEFAULT_COUNTRY = "JP"

DISPLAY_UPDATE_INTERVAL = 300  # 5 minutes in seconds
